data_dict = {
    "Doctor Who": "Adventure, Drama, Family",
    "Sherlock": "Crime, Drama, Mystery",
    "Downton Abbey": "Drama, Romance",
    "Peaky Blinders": "Crime, Drama",
    "Black Mirror": "Drama, Sci-Fi, Thriller",
    "The Crown": "Biography, Drama, History",
    "Fleabag": "Comedy, Drama",
    "Broadchurch": "Crime, Drama, Mystery",
    "Line of Duty": "Crime, Drama, Thriller",
    "The IT Crowd": "Comedy",
    "The Office (UK)": "Comedy",
    "Misfits": "Comedy, Drama, Fantasy",
    "Skins": "Drama",
    "Merlin": "Adventure, Drama, Fantasy",
    "Luther": "Crime, Drama, Mystery",
    "The Inbetweeners": "Comedy",
    "Top Gear": "Comedy, Talk-Show",
    "Bodyguard": "Action, Drama, Thriller",
    "Killing Eve": "Action, Adventure, Drama",
    "Call the Midwife": "Drama, History",
    "Spooks (MI-5)": "Action, Drama, Thriller",
    "Hinterland": "Crime, Drama, Mystery",
    "Being Human": "Comedy, Drama, Fantasy",
    "The Fall": "Crime, Drama, Thriller",
    "Torchwood": "Action, Drama, Sci-Fi",
    "The End of the F***ing World": "Adventure, Comedy, Crime",
    "Happy Valley": "Crime, Drama, Thriller",
    "Prime Suspect": "Crime, Drama, Mystery",
    "The Night Manager": "Crime, Drama, Thriller",
    "The Great British Bake Off": "Reality-TV",
    "The Last Kingdom": "Action, Drama, History",
    "Poldark": "Drama, History, Romance",
    "Life on Mars": "Crime, Drama, Mystery",
    "Ashes to Ashes": "Crime, Drama, Fantasy",
    "Inside No. 9": "Comedy, Drama, Horror",
    "The Thick of It": "Comedy",
    "Father Ted": "Comedy",
    "Monty Python's Flying Circus": "Comedy",
    "Utopia": "Drama, Mystery, Sci-Fi",
    "Absolutely Fabulous": "Comedy",
    "Red Dwarf": "Comedy, Sci-Fi",
    "Wallander": "Crime, Drama, Mystery",
    "Grantchester": "Crime, Drama, Mystery",
    "Endeavour": "Crime, Drama, Mystery",
    "Midsomer Murders": "Crime, Drama, Mystery",
    "Inspector Morse": "Crime, Drama, Mystery",
    "Gavin & Stacey": "Comedy, Romance",
    "Derry Girls": "Comedy",
    "The Graham Norton Show": "Comedy, Talk-Show",
    "Taskmaster": "Comedy, Game-Show",
    "QI": "Comedy, Game-Show",
    "The X Factor": "Music, Reality-TV",
    "Britain's Got Talent": "Reality-TV",
    "Have I Got News for You": "Comedy, News, Talk-Show",
    "Mock the Week": "Comedy",
    "The Chase": "Game-Show",
    "Pointless": "Game-Show",
    "Only Fools and Horses": "Comedy",
    "The Vicar of Dibley": "Comedy",
    "Yes Minister": "Comedy",
    "Yes, Prime Minister": "Comedy",
    "Are You Being Served?": "Comedy",
    "Dad's Army": "Comedy, War",
    "All Creatures Great and Small": "Comedy, Drama, Family",
    "Fawlty Towers": "Comedy",
    "The Young Ones": "Comedy",
    "Spaced": "Comedy",
    "Blackadder": "Comedy",
    "The League of Gentlemen": "Comedy, Horror",
    "Ripper Street": "Crime, Drama, Mystery",
    "Vera": "Crime, Drama, Mystery",
    "Silent Witness": "Crime, Drama, Mystery",
    "Cracker": "Crime, Drama, Mystery",
    "Whitechapel": "Crime, Drama, Mystery",
    "Poirot": "Crime, Drama, Mystery",
    "Jonathan Creek": "Crime, Drama, Mystery",
    "Agatha Christie's Marple": "Crime, Drama, Mystery",
    "The Adventures of Sherlock Holmes": "Crime, Drama, Mystery",
    "Waking the Dead": "Crime, Drama, Mystery",
    "Lewis": "Crime, Drama, Mystery",
    "DCI Banks": "Crime, Drama, Thriller",
    "New Tricks": "Comedy, Crime, Drama",
    "Death in Paradise": "Crime, Drama, Mystery",
    "Father Brown": "Crime, Drama, Mystery",
    "EastEnders": "Drama, Romance, Soap",
    "Coronation Street": "Drama, Romance, Soap",
    "Emmerdale": "Drama, Romance, Soap",
    "Hollyoaks": "Drama, Romance, Soap",
    "Casualty": "Drama, Soap",
    "Holby City": "Drama, Soap",
    "Waterloo Road": "Drama, Soap",
    "Grange Hill": "Drama, Family, Soap",
    "The Bill": "Crime, Drama, Soap",
    "Shameless": "Comedy, Drama",
    "Benidorm": "Comedy",
    "Cold Feet": "Comedy, Drama, Romance",
    "Doc Martin": "Comedy, Drama, Romance",
    "Outnumbered": "Comedy",
    "Green Wing": "Comedy",
    "Gogglebox": "Reality-TV"
}